/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Stockmanagement;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shital
 */
public class Biling extends javax.swing.JFrame {
    Connection con;
    double total,price,quantity;
    /**
     * Creates new form Biling
     */
    public Biling() {
        initComponents();
        setVisible(true);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String path = ("jdbc:mysql://localhost:3306/stockmanagement");
            con=DriverManager.getConnection(path,"root","deependentme");
        }catch(ClassNotFoundException | SQLException e){
            System.err.println(e);
        }
        
        try{
            PreparedStatement pst;
            ResultSet rs;
            pst = con.prepareStatement("select `ID`,`Product`,`Price`,`Up_Quantity`,`Expdate` from `calculate`");
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            table.getColumnModel().getColumn(0).setPreferredWidth(75);
            table.getColumnModel().getColumn(1).setPreferredWidth(230);
            table.getColumnModel().getColumn(2).setPreferredWidth(135);
            table.getColumnModel().getColumn(3).setPreferredWidth(135);
            table.getColumnModel().getColumn(4).setPreferredWidth(167);
        }
        catch(SQLException e){
            System.err.println(e);
        }
              
        try {
            double p;
            PreparedStatement pst1;
            ResultSet rs1;
            pst1 = con.prepareStatement("select * from `calculate`");
            rs1 = pst1.executeQuery();
            while(rs1.next()){
                p = rs1.getDouble("Quantity");
                price =rs1.getDouble("Price");
                quantity = rs1.getDouble("Up_Quantity");
                if((p-quantity) >= 0){
                    total = total +(price * quantity);
                }
            }
            show.setText(String.valueOf(total));
        } catch (SQLException e) {
            System.err.println(e);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Total Cost");

        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void update_table(){
        try {
            int uq,q;
            int quantity ;
            String uname ;
            PreparedStatement stmt;
            ResultSet rs;
            stmt = con.prepareStatement("select  * from `calculate`");
            rs = stmt.executeQuery();
            PreparedStatement  pst;
            pst = con.prepareStatement("update `details` set `Quantity` = ? where `Product Name` = ?");
            //ResultSet rs1;
            while(rs.next()){
                uq = rs.getInt("Up_Quantity");
                q = rs.getInt("Quantity");
                quantity = q - uq;
                uname = rs.getString("Product");
                
                if(quantity>=0){
                    
                    pst.setString(1,String.valueOf(quantity));
                    pst.setString(2, uname);
                    pst.executeUpdate();
                }
            }
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
    }
    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        try {
            today_record obj1= new today_record();
            obj1.transfer();
            update_table();
            dispose();
            Print obj = new Print();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Biling.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        new Biling();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbtn;
    private javax.swing.JLabel show;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
